[Editor]
MouseScrollingUnit = "pixel"

LineToScroll = 3

WindowGeometryBasedOnFontmetrics = true

Transparent = 1.0

FontFamily = "JetBrainsMonoNL Nerd Font"
FontSize = 11

DisableImeInNormal = true

HideMouseWhenTyping = true

SmoothScroll = true

DrawShadowForFloatWindow = true

fileOpenCmd = ":openExt"
