[Editor]
MouseScrollingUnit = "smart"

LineToScroll = 1

WindowGeometryBasedOnFontmetrics = false

Transparent = 1.0

FontFamily = "JetBrainsMonoNL Nerd Font"
FontSize = 12

DisableImeInNormal = true

HideMouseWhenTyping = true

SmoothScroll = false
DisableHorizontalScroll = false
DrawBorderForFloatWindow = true

# DrawShadowForFloatWindow = true

FileOpenCmd = ":openExt"
